import type { Metadata } from "next";
import ReduxProvider from "@/providers/ReduxProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body >
                <ReduxProvider>
                    {children}
                </ReduxProvider>
            </body>
        </html>
    );
}
